language: python
python:
    - 2.7
    - 3.4
    - pypy
before_install:
  - pip install codecov
install:
    - pip install .
    - pip install behave dont-fudge-up
script:
    - py.test -v tests
    - behave tests/features
after_success:
  - codecov
